### ISSUE TITLE
multiple instances in deployment

### ISSUE THREAD

**Issue by dgutson** [structurizr/dsl#184] opened 2022-12-15 18:14 UTC
I want to propose to be able to specify `many` or `N` as the argument of `instances`.

**Comment by dgutson** [comment] 2022-12-19 21:25
This is more relevant when the instances are auto-scalable.

**Comment by simonbrowndotje** [comment] 2022-12-20 10:54
Closing - duplicate of https://github.com/structurizr/structurizr/issues/106

**Closed by simonbrowndotje** 2022-12-20 10:54 UTC

**Comment by simonbrowndotje** [comment] 2023-01-05 17:55
This is now available, and here are some examples:

`instances 3` -- the existing supported value
`instances 0..5` -- a range with a bounded upper limit
`instances 2..N` or `instances 2..*` -- a range with an unbounded upper limit

**Comment by dgutson** [comment] 2023-01-05 18:03
Thanks!
